name: Build NextOS Repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # Используем официальный инструмент контейнеризации Arch Linux
      - name: Build Package inside Arch Linux
        uses: Jguer/aur-build-action@v1
        with:
          repo-name: 'os-core'
          gpg-key-id: 'D58CDACC916A86D0'
          packages: 'os-welcome'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
