name: Build System Package

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Запускаем сборку прямо внутри официального, всегда свежего контейнера Arch Linux
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      # 1. Скачиваем файлы из нашего репозитория GitHub в контейнер
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Подготавливаем чистый Arch Linux (обновляем ключи, ставим утилиты сборки)
      - name: Prepare Arch Environment
        run: |
          pacman -Syu --noconfirm --needed base-devel git sudo

      # 3. В Arch Linux запрещено собирать пакеты под root. Создаем временного пользователя build
      - name: Create Build User
        run: |
          useradd -m build
          echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R build:build .

      # 4. Собираем наш пакет nextos-welcome утилитой makepkg
      - name: Build Package
        run: |
          PACKAGES=("weirdcore-ui")
          
          for pkg in "${PACKAGES[@]}"; do
            echo "==> Сборка пакета: $pkg"
            chown -R build:build "$pkg"
            sudo -u build bash -c "cd $pkg && makepkg -s --noconfirm"
          done

      # 5. Импортируем твой GPG-ключ из секретов GitHub и подписываем пакет + создаем базу данных
      - name: Sign and Create Repo Database
        run: |
          mkdir -p output
          
          find . -name "*.pkg.tar.zst" -exec cp {} output/ \;
          
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          
          cd output
          repo-add --sign --key "D58CDACC916A86D0" weirdcore-system-core.db.tar.gz *.pkg.tar.zst

      # 6. Очищаем папку от мусора перед отправкой (оставляем только готовые файлы репозитория)
      - name: Fix Permissions
        run: |
          chown -R root:root .

      # 7. Выкатываем готовые файлы в ветку gh-pages (используем стандартный проверенный экшен)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages